=== VitexSoftware/MultiFlexi/doc/multiflexi.app.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MultiFlexi App Definition",
  "type": "object",
  "properties": {
    "image": { "type": "string" },
    "name": { "type": "string" },
    "description": { "type": "string" },
    "executable": { "type": "string" },
    "setup": { "type": "string" },
    "cmdparams": { "type": "string" },
    "deploy": { "type": "string" },
    "homepage": { "type": "string" },
    "ociimage": { "type": "string" },
    "uuid": { "type": "string" },
    "topics": { "type": "string" },
    "requirements": { "type": "string" },
    "version": { "type": "string" },
    "multiflexi": { "type": "string" },
    "environment": {
      "type": "object",
      "patternProperties": {
        "^[A-Z0-9_]+$": {
          "type": "object",
          "properties": {
            "type": { "type": "string" },
            "description": { "type": "string" },
            "defval": {},
            "required": { "type": "boolean" },
            "hint": { "type": "string" },
            "options": {
              "type": ["object", "array"]
            }
          },
          "additionalProperties": true
        }
      }
    }
  },
  "required": [
    "name",
    "description",
    "executable",
    "environment"
  ],
  "additionalProperties": true
}

=== VitexSoftware/MultiFlexi/tests/multiflexi_probe.multiflexi.app.json
{
    "image": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgaWQ9InN2ZzM0MzAiCiAgIHdpZHRoPSI4MDAiCiAgIGhlaWdodD0iODAwIgogICB2aWV3Qm94PSIwIDAgNzk5Ljk5OTc0IDgwMC4wMDEwNCIKICAgdmVyc2lvbj0iMS4xIgogICBzb2RpcG9kaTpkb2NuYW1lPSJtdWx0aWZsZXhpLXByb2JlLnN2ZyIKICAgaW5rc2NhcGU6dmVyc2lvbj0iMS4yLjIgKGIwYTg0ODY1NDEsIDIwMjItMTItMDEpIgogICB4bWxuczppbmtzY2FwZT0iaHR0cDovL3d3dy5pbmtzY2FwZS5vcmcvbmFtZXNwYWNlcy9pbmtzY2FwZSIKICAgeG1sbnM6c29kaXBvZGk9Imh0dHA6Ly9zb2RpcG9kaS5zb3VyY2Vmb3JnZS5uZXQvRFREL3NvZGlwb2RpLTAuZHRkIgogICB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyIKICAgeG1sbnM6Y2M9Imh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL25zIyIKICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIj4KICA8bWV0YWRhdGEKICAgICBpZD0ibWV0YWRhdGE0MSI+CiAgICA8cmRmOlJERj4KICAgICAgPGNjOldvcmsKICAgICAgICAgcmRmOmFib3V0PSIiPgogICAgICAgIDxkYzpmb3JtYXQ+aW1hZ2Uvc3ZnK3htbDwvZGM6Zm9ybWF0PgogICAgICAgIDxkYzp0eXBlCiAgICAgICAgICAgcmRmOnJlc291cmNlPSJodHRwOi8vcHVybC5vcmcvZGMvZGNtaXR5cGUvU3RpbGxJbWFnZSIgLz4KICAgICAgPC9jYzpXb3JrPgogICAgPC9yZGY6UkRGPgogIDwvbWV0YWRhdGE+CiAgPHNvZGlwb2RpOm5hbWVkdmlldwogICAgIHBhZ2Vjb2xvcj0iI2ZmZmZmZiIKICAgICBib3JkZXJjb2xvcj0iIzY2NjY2NiIKICAgICBib3JkZXJvcGFjaXR5PSIxIgogICAgIG9iamVjdHRvbGVyYW5jZT0iMTAiCiAgICAgZ3JpZHRvbGVyYW5jZT0iMTAiCiAgICAgZ3VpZGV0b2xlcmFuY2U9IjEwIgogICAgIGlua3NjYXBlOnBhZ2VvcGFjaXR5PSIwIgogICAgIGlua3NjYXBlOnBhZ2VzaGFkb3c9IjIiCiAgICAgaW5rc2NhcGU6d2luZG93LXdpZHRoPSIxOTIwIgogICAgIGlua3NjYXBlOndpbmRvdy1oZWlnaHQ9IjExMjAiCiAgICAgaWQ9Im5hbWVkdmlldzM5IgogICAgIHNob3dncmlkPSJmYWxzZSIKICAgICBpbmtzY2FwZTp6b29tPSIwLjYxNTIyODIiCiAgICAgaW5rc2NhcGU6Y3g9IjEwNjAuNTgyMSIKICAgICBpbmtzY2FwZTpjeT0iNTkxLjY1MDM4IgogICAgIGlua3NjYXBlOndpbmRvdy14PSIwIgogICAgIGlua3NjYXBlOndpbmRvdy15PSIwIgogICAgIGlua3NjYXBlOndpbmRvdy1tYXhpbWl6ZWQ9IjEiCiAgICAgaW5rc2NhcGU6Y3VycmVudC1sYXllcj0ic3ZnMzQzMCIKICAgICBpbmtzY2FwZTpzaG93cGFnZXNoYWRvdz0iMiIKICAgICBpbmtzY2FwZTpwYWdlY2hlY2tlcmJvYXJkPSIwIgogICAgIGlua3NjYXBlOmRlc2tjb2xvcj0iI2QxZDFkMSIgLz4KICA8ZGVmcwogICAgIGlkPSJkZWZzMzQzNCI+CiAgICA8Y2xpcFBhdGgKICAgICAgIGlkPSJjbGlwUGF0aDM0NDQiPgogICAgICA8cGF0aAogICAgICAgICBpZD0icGF0aDM0NDYiCiAgICAgICAgIGQ9Ik0gMTEuNTIsMTYyIEMgMTEuNTIsODEuNjc3IDEzNS4zMDcsMTYuNTYgMjg4LDE2LjU2IDQ0MC42OTMsMTYuNTYgNTY0LjQ4LDgxLjY3OCA1NjQuNDgsMTYyIDU2NC40OCwyNDIuMzIyIDQ0MC42OTMsMzA3LjQ0IDI4OCwzMDcuNDQgMTM1LjMwNywzMDcuNDQgMTEuNTIsMjQyLjMyIDExLjUyLDE2MiIKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIgLz4KICAgIDwvY2xpcFBhdGg+CiAgICA8cmFkaWFsR3JhZGllbnQKICAgICAgIGlkPSJyYWRpYWxHcmFkaWVudDM0NTIiCiAgICAgICBjeD0iMCIKICAgICAgIGN5PSIwIgogICAgICAgcj0iMSIKICAgICAgIGZ4PSIwIgogICAgICAgZnk9IjAiCiAgICAgICBncmFkaWVudFRyYW5zZm9ybT0ibWF0cml4KDM2My4wNiwwLDAsLTM2My4wNiwxNzcuNTIsMjU2LjMxKSIKICAgICAgIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIgogICAgICAgc3ByZWFkTWV0aG9kPSJwYWQiPgogICAgICA8c3RvcAogICAgICAgICBpZD0ic3RvcDM0NTQiCiAgICAgICAgIG9mZnNldD0iMCIKICAgICAgICAgc3RvcC1jb2xvcj0iI2FlYjJkNSIgLz4KICAgICAgPHN0b3AKICAgICAgICAgaWQ9InN0b3AzNDU2IgogICAgICAgICBvZmZzZXQ9IjAuMyIKICAgICAgICAgc3RvcC1jb2xvcj0iI2FlYjJkNSIgLz4KICAgICAgPHN0b3AKICAgICAgICAgaWQ9InN0b3AzNDU4IgogICAgICAgICBvZmZzZXQ9IjAuNzUiCiAgICAgICAgIHN0b3AtY29sb3I9IiM0ODRjODkiIC8+CiAgICAgIDxzdG9wCiAgICAgICAgIGlkPSJzdG9wMzQ2MCIKICAgICAgICAgb2Zmc2V0PSIxIgogICAgICAgICBzdG9wLWNvbG9yPSIjNDg0Yzg5IiAvPgogICAgPC9yYWRpYWxHcmFkaWVudD4KICAgIDxjbGlwUGF0aAogICAgICAgaWQ9ImNsaXBQYXRoMzQ2OCI+CiAgICAgIDxwYXRoCiAgICAgICAgIGlkPSJwYXRoMzQ3MCIKICAgICAgICAgZD0iTSAwLDMyNCBIIDU3NiBWIDAgSCAwIFoiCiAgICAgICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiIC8+CiAgICA8L2NsaXBQYXRoPgogICAgPGNsaXBQYXRoCiAgICAgICBpZD0iY2xpcFBhdGgzNDgwIj4KICAgICAgPHBhdGgKICAgICAgICAgaWQ9InBhdGgzNDgyIgogICAgICAgICBkPSJNIDAsMzI0IEggNTc2IFYgMCBIIDAgWiIKICAgICAgICAgaW5rc2NhcGU6Y29ubmVjdG9yLWN1cnZhdHVyZT0iMCIgLz4KICAgIDwvY2xpcFBhdGg+CiAgICA8ZmlsdGVyCiAgICAgICBzdHlsZT0iY29sb3ItaW50ZXJwb2xhdGlvbi1maWx0ZXJzOnNSR0IiCiAgICAgICBpbmtzY2FwZTpsYWJlbD0iRHJvcCBTaGFkb3ciCiAgICAgICBpZD0iZmlsdGVyNDYyMiIKICAgICAgIHg9Ii0wLjEyMTUxODYiCiAgICAgICB5PSItMC4yMTA1MTMzNCIKICAgICAgIHdpZHRoPSIxLjI5MzY3IgogICAgICAgaGVpZ2h0PSIxLjUwODc0MDYiPgogICAgICA8ZmVGbG9vZAogICAgICAgICBmbG9vZC1vcGFjaXR5PSIwLjQ5ODAzOSIKICAgICAgICAgZmxvb2QtY29sb3I9InJnYigwLDAsMCkiCiAgICAgICAgIHJlc3VsdD0iZmxvb2QiCiAgICAgICAgIGlkPSJmZUZsb29kNDYxMiIgLz4KICAgICAgPGZlQ29tcG9zaXRlCiAgICAgICAgIGluPSJmbG9vZCIKICAgICAgICAgaW4yPSJTb3VyY2VHcmFwaGljIgogICAgICAgICBvcGVyYXRvcj0iaW4iCiAgICAgICAgIHJlc3VsdD0iY29tcG9zaXRlMSIKICAgICAgICAgaWQ9ImZlQ29tcG9zaXRlNDYxNCIgLz4KICAgICAgPGZlR2F1c3NpYW5CbHVyCiAgICAgICAgIGluPSJjb21wb3NpdGUxIgogICAgICAgICBzdGREZXZpYXRpb249IjYiCiAgICAgICAgIHJlc3VsdD0iYmx1ciIKICAgICAgICAgaWQ9ImZlR2F1c3NpYW5CbHVyNDYxNiIgLz4KICAgICAgPGZlT2Zmc2V0CiAgICAgICAgIGR4PSI2IgogICAgICAgICBkeT0iNiIKICAgICAgICAgcmVzdWx0PSJvZmZzZXQiCiAgICAgICAgIGlkPSJmZU9mZnNldDQ2MTgiIC8+CiAgICAgIDxmZUNvbXBvc2l0ZQogICAgICAgICBpbj0iU291cmNlR3JhcGhpYyIKICAgICAgICAgaW4yPSJvZmZzZXQiCiAgICAgICAgIG9wZXJhdG9yPSJvdmVyIgogICAgICAgICByZXN1bHQ9ImZiU291cmNlR3JhcGhpYyIKICAgICAgICAgaWQ9ImZlQ29tcG9zaXRlNDYyMCIgLz4KICAgICAgPGZlQ29sb3JNYXRyaXgKICAgICAgICAgcmVzdWx0PSJmYlNvdXJjZUdyYXBoaWNBbHBoYSIKICAgICAgICAgaW49ImZiU291cmNlR3JhcGhpYyIKICAgICAgICAgdmFsdWVzPSIwIDAgMCAtMSAwIDAgMCAwIC0xIDAgMCAwIDAgLTEgMCAwIDAgMCAxIDAiCiAgICAgICAgIGlkPSJmZUNvbG9yTWF0cml4NDYyNCIgLz4KICAgICAgPGZlRmxvb2QKICAgICAgICAgaWQ9ImZlRmxvb2Q0NjI2IgogICAgICAgICBmbG9vZC1vcGFjaXR5PSIwLjQ5ODAzOSIKICAgICAgICAgZmxvb2QtY29sb3I9InJnYigwLDAsMCkiCiAgICAgICAgIHJlc3VsdD0iZmxvb2QiCiAgICAgICAgIGluPSJmYlNvdXJjZUdyYXBoaWMiIC8+CiAgICAgIDxmZUNvbXBvc2l0ZQogICAgICAgICBpbjI9ImZiU291cmNlR3JhcGhpYyIKICAgICAgICAgaWQ9ImZlQ29tcG9zaXRlNDYyOCIKICAgICAgICAgaW49ImZsb29kIgogICAgICAgICBvcGVyYXRvcj0iaW4iCiAgICAgICAgIHJlc3VsdD0iY29tcG9zaXRlMSIgLz4KICAgICAgPGZlR2F1c3NpYW5CbHVyCiAgICAgICAgIGlkPSJmZUdhdXNzaWFuQmx1cjQ2MzAiCiAgICAgICAgIGluPSJjb21wb3NpdGUxIgogICAgICAgICBzdGREZXZpYXRpb249IjYiCiAgICAgICAgIHJlc3VsdD0iYmx1ciIgLz4KICAgICAgPGZlT2Zmc2V0CiAgICAgICAgIGlkPSJmZU9mZnNldDQ2MzIiCiAgICAgICAgIGR4PSI2IgogICAgICAgICBkeT0iNiIKICAgICAgICAgcmVzdWx0PSJvZmZzZXQiIC8+CiAgICAgIDxmZUNvbXBvc2l0ZQogICAgICAgICBpbjI9Im9mZnNldCIKICAgICAgICAgaWQ9ImZlQ29tcG9zaXRlNDYzNCIKICAgICAgICAgaW49ImZiU291cmNlR3JhcGhpYyIKICAgICAgICAgb3BlcmF0b3I9Im92ZXIiCiAgICAgICAgIHJlc3VsdD0iZmJTb3VyY2VHcmFwaGljIiAvPgogICAgICA8ZmVDb2xvck1hdHJpeAogICAgICAgICByZXN1bHQ9ImZiU291cmNlR3JhcGhpY0FscGhhIgogICAgICAgICBpbj0iZmJTb3VyY2VHcmFwaGljIgogICAgICAgICB2YWx1ZXM9IjAgMCAwIC0xIDAgMCAwIDAgLTEgMCAwIDAgMCAtMSAwIDAgMCAwIDEgMCIKICAgICAgICAgaWQ9ImZlQ29sb3JNYXRyaXg0NjM2IiAvPgogICAgICA8ZmVGbG9vZAogICAgICAgICBpZD0iZmVGbG9vZDQ2MzgiCiAgICAgICAgIGZsb29kLW9wYWNpdHk9IjAuNDk4MDM5IgogICAgICAgICBmbG9vZC1jb2xvcj0icmdiKDAsMCwwKSIKICAgICAgICAgcmVzdWx0PSJmbG9vZCIKICAgICAgICAgaW49ImZiU291cmNlR3JhcGhpYyIgLz4KICAgICAgPGZlQ29tcG9zaXRlCiAgICAgICAgIGluMj0iZmJTb3VyY2VHcmFwaGljIgogICAgICAgICBpZD0iZmVDb21wb3NpdGU0NjQwIgogICAgICAgICBpbj0iZmxvb2QiCiAgICAgICAgIG9wZXJhdG9yPSJpbiIKICAgICAgICAgcmVzdWx0PSJjb21wb3NpdGUxIiAvPgogICAgICA8ZmVHYXVzc2lhbkJsdXIKICAgICAgICAgaWQ9ImZlR2F1c3NpYW5CbHVyNDY0MiIKICAgICAgICAgaW49ImNvbXBvc2l0ZTEiCiAgICAgICAgIHN0ZERldmlhdGlvbj0iNiIKICAgICAgICAgcmVzdWx0PSJibHVyIiAvPgogICAgICA8ZmVPZmZzZXQKICAgICAgICAgaWQ9ImZlT2Zmc2V0NDY0NCIKICAgICAgICAgZHg9IjYiCiAgICAgICAgIGR5PSI2IgogICAgICAgICByZXN1bHQ9Im9mZnNldCIgLz4KICAgICAgPGZlQ29tcG9zaXRlCiAgICAgICAgIGluMj0ib2Zmc2V0IgogICAgICAgICBpZD0iZmVDb21wb3NpdGU0NjQ2IgogICAgICAgICBpbj0iZmJTb3VyY2VHcmFwaGljIgogICAgICAgICBvcGVyYXRvcj0ib3ZlciIKICAgICAgICAgcmVzdWx0PSJjb21wb3NpdGUyIiAvPgogICAgPC9maWx0ZXI+CiAgICA8ZmlsdGVyCiAgICAgICBzdHlsZT0iY29sb3ItaW50ZXJwb2xhdGlvbi1maWx0ZXJzOnNSR0IiCiAgICAgICBpbmtzY2FwZTpsYWJlbD0iQ29sb3IgU2hpZnQiCiAgICAgICBpZD0iZmlsdGVyMzg2MSI+CiAgICAgIDxmZUNvbG9yTWF0cml4CiAgICAgICAgIHR5cGU9Imh1ZVJvdGF0ZSIKICAgICAgICAgdmFsdWVzPSIxMTIiCiAgICAgICAgIHJlc3VsdD0iY29sb3IxIgogICAgICAgICBpZD0iZmVDb2xvck1hdHJpeDM4NTciIC8+CiAgICAgIDxmZUNvbG9yTWF0cml4CiAgICAgICAgIHR5cGU9InNhdHVyYXRlIgogICAgICAgICB2YWx1ZXM9IjAuNiIKICAgICAgICAgcmVzdWx0PSJmYlNvdXJjZUdyYXBoaWMiCiAgICAgICAgIGlkPSJmZUNvbG9yTWF0cml4Mzg1OSIgLz4KICAgICAgPGZlQ29sb3JNYXRyaXgKICAgICAgICAgcmVzdWx0PSJmYlNvdXJjZUdyYXBoaWNBbHBoYSIKICAgICAgICAgaW49ImZiU291cmNlR3JhcGhpYyIKICAgICAgICAgdmFsdWVzPSIwIDAgMCAtMSAwIDAgMCAwIC0xIDAgMCAwIDAgLTEgMCAwIDAgMCAxIDAiCiAgICAgICAgIGlkPSJmZUNvbG9yTWF0cml4Mzg2MyIgLz4KICAgICAgPGZlQ29sb3JNYXRyaXgKICAgICAgICAgaWQ9ImZlQ29sb3JNYXRyaXgzODY1IgogICAgICAgICB0eXBlPSJodWVSb3RhdGUiCiAgICAgICAgIHZhbHVlcz0iMTEyIgogICAgICAgICByZXN1bHQ9ImNvbG9yMSIKICAgICAgICAgaW49ImZiU291cmNlR3JhcGhpYyIgLz4KICAgICAgPGZlQ29sb3JNYXRyaXgKICAgICAgICAgaWQ9ImZlQ29sb3JNYXRyaXgzODY3IgogICAgICAgICB0eXBlPSJzYXR1cmF0ZSIKICAgICAgICAgdmFsdWVzPSIwLjYiCiAgICAgICAgIHJlc3VsdD0iY29sb3IyIiAvPgogICAgPC9maWx0ZXI+CiAgICA8ZmlsdGVyCiAgICAgICBzdHlsZT0iY29sb3ItaW50ZXJwb2xhdGlvbi1maWx0ZXJzOnNSR0IiCiAgICAgICBpbmtzY2FwZTpsYWJlbD0iQ29sb3IgU2hpZnQiCiAgICAgICBpZD0iZmlsdGVyMzg3MyI+CiAgICAgIDxmZUNvbG9yTWF0cml4CiAgICAgICAgIHR5cGU9Imh1ZVJvdGF0ZSIKICAgICAgICAgdmFsdWVzPSIxMTIiCiAgICAgICAgIHJlc3VsdD0iY29sb3IxIgogICAgICAgICBpZD0iZmVDb2xvck1hdHJpeDM4NjkiIC8+CiAgICAgIDxmZUNvbG9yTWF0cml4CiAgICAgICAgIHR5cGU9InNhdHVyYXRlIgogICAgICAgICB2YWx1ZXM9IjAuNiIKICAgICAgICAgcmVzdWx0PSJmYlNvdXJjZUdyYXBoaWMiCiAgICAgICAgIGlkPSJmZUNvbG9yTWF0cml4Mzg3MSIgLz4KICAgICAgPGZlQ29sb3JNYXRyaXgKICAgICAgICAgcmVzdWx0PSJmYlNvdXJjZUdyYXBoaWNBbHBoYSIKICAgICAgICAgaW49ImZiU291cmNlR3JhcGhpYyIKICAgICAgICAgdmFsdWVzPSIwIDAgMCAtMSAwIDAgMCAwIC0xIDAgMCAwIDAgLTEgMCAwIDAgMCAxIDAiCiAgICAgICAgIGlkPSJmZUNvbG9yTWF0cml4MzkxMSIgLz4KICAgICAgPGZlQ29sb3JNYXRyaXgKICAgICAgICAgaWQ9ImZlQ29sb3JNYXRyaXgzOTEzIgogICAgICAgICB0eXBlPSJodWVSb3RhdGUiCiAgICAgICAgIHZhbHVlcz0iMzIzIgogICAgICAgICByZXN1bHQ9ImNvbG9yMSIKICAgICAgICAgaW49ImZiU291cmNlR3JhcGhpYyIgLz4KICAgICAgPGZlQ29sb3JNYXRyaXgKICAgICAgICAgaWQ9ImZlQ29sb3JNYXRyaXgzOTE1IgogICAgICAgICB0eXBlPSJzYXR1cmF0ZSIKICAgICAgICAgdmFsdWVzPSIwLjYxIgogICAgICAgICByZXN1bHQ9ImNvbG9yMiIgLz4KICAgIDwvZmlsdGVyPgogICAgPGZpbHRlcgogICAgICAgc3R5bGU9ImNvbG9yLWludGVycG9sYXRpb24tZmlsdGVyczpzUkdCIgogICAgICAgaW5rc2NhcGU6bGFiZWw9IkNvbG9yIFNoaWZ0IgogICAgICAgaWQ9ImZpbHRlcjQwMTciCiAgICAgICB4PS
